modLoader = "javafml"
loaderVersion = "[4,)"
license = "All-Rights-Reserved"

[[mods]]
modId = "yuhutian"
version = "${version}"
displayName = "玉壶天"
description = "玉壶天 —— 自定义虚空维度与传送物品"

[[dependencies.yuhutian]]
modId = "forge"
mandatory = true
versionRange = "[52,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yuhutian]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yuhutian]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.0,)"
ordering = "AFTER"
side = "BOTH"
